# LAB1: NumPy Exercises 


#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [ ]:
#using numpy to create an array of zeros
my_array = np.zeros(10)
print(my_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [ ]:
#using numpy to create an array of zeros
my_array = np.ones(10)
print(my_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [ ]:
#creating a list of 10 1s then performing a multiplication operation to make it into fives
np_array = np.ones(10) * 5
print(np_array)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [ ]:
#using numpy arrange to create an array of numbers from 10 to 50
np_array = np.arange(10,51)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Create an array of all the even integers from 10 to 50

In [ ]:
#creating an array of only even numbers from 10 to 50 by adding a step of 2
np_array = np.arange(10, 51, 2)
np_array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
#creating an array of 0 to 9 and reshaping it into a 3x3 matrix
np_matrix = np.arange(0,9)
np_matrix = np_matrix.reshape(3,3)
np_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Use NumPy to generate a random number between 0 and 1

In [97]:
#calling a random number generator to create a random number between 0 and 1
np_random = np.random.randint(0,1)
np_random

0

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
#creating an array of random numbers between 1 and 50 with a size of 25
# using the random number generator
np_random = np.random.randint(1,50,25)
np_random

array([21, 30, 23, 27,  3, 43, 19, 46, 17, 35, 31, 24, 41, 34, 46, 37, 36,
       38, 42, 34, 39, 31, 13,  6,  3])

#### Create the following matrix:

In [ ]:
#using linspace to create an array of 100 numbers between 0.01 and 1.0
#then reshaping it into a 10x10 matrix
np_matrix = np.linspace(0.01,1.0,100)
np_matrix = np_matrix.reshape(10,10)
np_matrix

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
#using linspace to create an array of 20 numbers between 0 and 1.0
np_matrix = np.linspace(0,1,20)
np_matrix

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [98]:
#creating an array of numbers from 1 to 25
#then reshaping it into a 5x5 matrix
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Write a code that creates the following output**

In [ ]:
#creating an array of 1 to 25 then reshaping it into a 5x5 matrix
#then slicing the matrix to get the last 3 rows and last 4 columns
mat = np.arange(1,26).reshape(5,5)
mat = mat[2:, 1:]
mat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [100]:
mat[1][3]

np.int64(20)

In [ ]:
#creating an array of 1 to 25, the reshaping it into a 5x5 matrix
#then slicing the matrix to get the first 3 rows and the second column
mat = np.arange(1,26).reshape(5,5)
mat = mat[0:3,1:2]
mat

array([[ 2],
       [ 7],
       [12]])

In [ ]:
#creating an array of 1 to 25
#then reshaping it into a 5x5 matrix
#then slicing the matrix to get the last row
mat = np.arange(1,26).reshape(5,5)
mat = mat[4:,:]
mat

array([[21, 22, 23, 24, 25]])

In [ ]:
#creating an array of 1 to 25
#then reshaping it into a 5x5 matrix
#then slicing the matrix to get the last 2 rows
mat = np.arange(1,26).reshape(5,5)
mat = mat[3:,:]
mat

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
#creating an array of 1 to 5, and getting the sum of the entire array
mat = np.arange(1,26).reshape(5,5)
mat.sum()

np.int64(325)

#### Get the sum of all the columns in mat

In [ ]:
#using numpy sum operation and axis to get the sun of the columns
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

#### Broadcasting

Given a=np.arange(3).reshape(3, 1) and b=np.arange(3):

- Predict the result of a + b without running the code.

- Explain the broadcasting rules at play.

- Create the arrays and run the results

- Implement a solution that would not rely on broadcasting (using np.tile or similar).

In [ ]:
#prediction 
#a = [[0], [1], [2]]
#b = [0, 1, 2]
#each element of a is added to each element of b
#[[0+0, 0+1, 0+2],
# [1+0, 1+1, 1+2],
# [2+0, 2+1, 2+2]]
# result is a 3x3 matrix
#[[0, 1, 2],
# [1, 2, 3],
# [2, 3, 4]]

#Broadcasting allows numpy to arithemetic operations on arrays of different shapes,
#which enables smaller arrays to match the shape of larger arrays.


# a=np.arange(3).reshape(3, 1)
# b=np.arange(3)
# result = a + b
# result

#solution without broadcasting using loops

#arrange the arrays and matrix
a=np.arange(3).reshape(3, 1)
b=np.arange(3)

#creating a result matrix of zeros with the shape of a and b
result = np.zeros((a.shape[0], b.shape[0]), dtype=int)
#using nested loops to iterate through both arrays and perform the addition
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        result[i,j] = a[i,0] + b[j] #this ensure all elements of a are added to all elements of b
result


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Great Job!